name: Unit tests
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  test_SPORTMEN:
    runs-on: ubuntu-latest
    environment: secret
    services:

      postgres-auth:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 6000:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      postgres-sub:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 6400:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      postgres-sport:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 6200:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      postgres-host:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 6600:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker pull us-east1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/repo/sportmen
      - name: Test
        run: docker run -d --rm --network="host" -p 6250:80 -e SPORTMEN_DB_HOST='localhost' -e SPORTMEN_DB_PORT='6200' -e SPORTMEN_DB_PASSWORD='postgres' -e SPORTMEN_DB_USER='postgres' -e SPORTMEN_DB_NAME='postgres' -e AUTH_HOST='http://localhost:6050' -e AUTH_PATH_AUTH='/auth/auth' us-east1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/repo/sportmen
      - name: Ping
        run: curl localhost:6250/sportmen/ping