name: Unit tests
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  test_orchestrator:
    runs-on: ubuntu-latest
    environment: secret
    services:

      postgres-auth:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 6000:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      subscription_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 6400:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      subscription:
        image: us-east1-docker.pkg.dev/composite-bruin-419400/repo/subscription
        env:
          AUTH_HOST: http://localhost:6050
          AUTH_PATH_AUTH: /auth/auth
          SUBSCRIPTION_DB_USER: postgres
          SUBSCRIPTION_DB_HOST: subscription_db
          SUBSCRIPTION_DB_NAME: postgres
          SUBSCRIPTION_DB_PASSWORD: postgres
          SUBSCRIPTION_DB_PORT: 5432
        ports:
          - 6450:80
   

      partner_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 6600:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      partner:
        image: us-east1-docker.pkg.dev/composite-bruin-419400/repo/partner
        env:
          AUTH_HOST: http://localhost:6050
          AUTH_PATH_AUTH: /auth/auth
          AUTH_PORT: 6050
          PARTNER_DB_USER: postgres
          PARTNER_DB_HOST: partner_db
          PARTNER_DB_NAME: postgres
          PARTNER_DB_PASSWORD: postgres
          PARTNER_DB_PORT: 5432
        ports:
          - 6650:80
   
      sportmen_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 6200:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      sportmen:
        image: us-east1-docker.pkg.dev/composite-bruin-419400/repo/sportmen
        env:
          AUTH_HOST: http://localhost:6050
          AUTH_PATH_AUTH: /auth/auth
          SPORTMEN_DB_USER: postgres
          SPORTMEN_DB_HOST: sportmen_db
          SPORTMEN_DB_NAME: postgres
          SPORTMEN_DB_PASSWORD: postgres
          SPORTMEN_DB_PORT: 5432
        ports:
          - 6250:80
 

    steps:
      - uses: actions/checkout@v1
      - name: Ping Sportmen
        run: curl  -X GET 'localhost:6250/sportmen/ping'
      - name: Ping Partner
        run: curl  -X GET 'localhost:6650/partner/ping'
      - name: Ping Partner
        run: curl  -X GET 'localhost:6450/susbcription/ping'